# Generated by Django 3.1.7 on 2021-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20210401_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketstatus',
            field=models.CharField(choices=[('new', 'new'), ('in_process', 'in_process'), ('invalid', 'invalid'), ('finished', 'finished')], default='new', max_length=25),
        ),
    ]
